# Generated by Django 4.0.3 on 2022-03-20 16:37

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # This migration depends on the CI extension
        ('horses', '0002_alter_horse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('paddock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddocks.paddock')),
            ],
        ),
    ]
