# Generated by Django 4.0.3 on 2022-03-13 22:13

import django.contrib.postgres.fields.citext
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=50, unique=True),
        ),
    ]
